name: Pipeline Personalizado

on:
  push:
    branches: [develop, feature/*]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Detect branch
      run: |
        echo "Rama actual: ${{ github.ref_name }}"
    - name: Detect OS version
      run: |
        echo "Imprimiendo la version de Sistema Operativo:"
        cat /etc/os-release
  
  job2:
    runs-on: ubuntu-22.04
    steps:
    - name: OS version
      run: |
        cat /etc/os-release